import { binToHex, sha256, utf8ToBin } from '@bitauth/libauth';
import {
  BuildOptions,
  ContractKind,
  FeatureFlag,
  FieldDef,
  GeneratedContract,
  checkFeatureConstraints,
  collectFieldDefs,
  normalizeValue,
  validateAllFields,
} from './schema';
import { collectBlockParams, dedupeParams } from './blocks';

function fieldToParam(field: FieldDef): string {
  switch (field.type) {
    case 'pubkey':
      return `pubkey ${field.id}`;
    case 'bool':
    case 'int':
    case 'blockHeight':
    case 'unixTime':
      return `int ${field.id}`;
    case 'bytes20':
      return `bytes20 ${field.id}`;
    case 'bytes32':
    case 'tokenCategory':
      return `bytes32 ${field.id}`;
    case 'cashAddress':
      return `bytes ${field.id}LockingBytecode`;
    case 'enum':
    default:
      return `int ${field.id}`;
  }
}

function renderParams(fields: FieldDef[], extra: string[] = []): string {
  const ordered = dedupeParams([...fields.map(fieldToParam), ...extra]);
  return ordered.join(',\n    ');
}

function quoteLiteral(val: string | number | boolean): string {
  if (typeof val === 'boolean') return val ? '1' : '0';
  if (typeof val === 'number') return Number.isFinite(val) ? String(Math.trunc(val)) : '0';
  const text = String(val);
  if (/^-?\d+$/.test(text)) return text;
  return `"${text.replace(/"/g, '\\"')}"`;
}

function renderMeta(fields: Record<string, string | number | boolean>): string {
  const entries = Object.entries(fields).sort(([a], [b]) => a.localeCompare(b));
  if (!entries.length) return '// No user fields configured.';
  return entries
    .map(([k, v]) => `// ${k}: ${quoteLiteral(v)}`)
    .join('\n');
}

export function quickLint(source: string): string[] {
  const warnings: string[] = [];
  const bytes = new TextEncoder().encode(source).length;
  const requires = (source.match(/\brequire\(/g) || []).length;
  const funcs = (source.match(/\bfunction\s+\w+/g) || []).length;
  const approxOps = requires * 3 + funcs * 5 + 10;

  if (bytes > 6000) warnings.push(`Contract source is large (${bytes} bytes).`);
  if (approxOps > 180) warnings.push(`Estimated opcode pressure is high (${approxOps}/201).`);
  if (source.includes('require(true);')) warnings.push('Contains placeholder guards; review before deployment.');
  return warnings;
}

function hashSource(source: string): string {
  return binToHex(sha256.hash(utf8ToBin(source)));
}

function selectedFeatures(kind: ContractKind, enabled: Record<string, boolean>): FeatureFlag[] {
  return kind.features.filter((feature) => enabled[feature.id]);
}

export interface GenerateResult extends GeneratedContract {
  fieldErrors: Record<string, string>;
  constraintErrors: string[];
  params: string;
}

export function generate(kind: ContractKind, opts: BuildOptions): GenerateResult {
  const enabled = opts.enabled ?? {};
  const fields = opts.fields ?? {};
  const selected = selectedFeatures(kind, enabled);
  const constraintErrors = checkFeatureConstraints(kind, enabled);
  const visibleFields = collectFieldDefs(kind, enabled);
  const fieldErrors = validateAllFields(kind, enabled, fields);
  const normalized: Record<string, string | number | boolean> = {};
  for (const def of visibleFields) normalized[def.id] = normalizeValue(def, fields[def.id]);

  const features = selected.map((f) => f.id);
  const built = kind.build({ fields: normalized, enabled });
  const blockParams = collectBlockParams(features);
  const params = renderParams(visibleFields, blockParams);
  const source = [
    'pragma cashscript ^0.13.0;',
    '',
    '// Generated by NexWizard v2 (UTXO composer)',
    renderMeta(normalized),
    '',
    `contract ${kind.name}(`,
    `    ${params}`,
    ') {',
    built.source.trim(),
    '}',
  ].join('\n');

  const warnings = [...quickLint(source), ...(built.warnings ?? [])];
  return {
    source,
    hash: hashSource(source),
    warnings,
    fieldErrors,
    constraintErrors,
    params,
  };
}
