/**
 * Generates supabase/functions/_shared/registryGate.ts from lib/registryGate.ts.
 * Run: npm run sync:registry-gate
 * CI check: npm run sync:registry-gate -- --check
 */
import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const LIB_PATH = join(ROOT, 'lib', 'registryGate.ts');
const OUT_PATH = join(ROOT, 'supabase', 'functions', '_shared', 'registryGate.ts');

const DENO_HEADER = `// Deno edge bundle — generated by scripts/sync-registry-gate.ts — do not edit by hand.

interface Vulnerability {
  severity: string;
}

interface AuditReport {
  score?: number;
  total_score?: number;
  deployment_allowed?: boolean;
  vulnerabilities?: Vulnerability[];
  metadata?: { contract_hash?: string };
  timestamp?: number;
}

interface ContractArtifact {
  bytecode?: string;
}

`;

const CLIENT_ONLY = new Set([
  'DeployGateResult',
  'countHighOrCritical',
  'stampAuditWithSourceHash',
  'getContractSourceFromProject',
  'resolveAuditReportForPublish',
  'canDeploy',
]);

/** Remove export block; brace match starts at function body `{`, not type literals in params. */
function removeExportBlock(source: string, exportName: string): string {
  const fnRe = new RegExp(`export (async )?function ${exportName}\\b`);
  const ifaceRe = new RegExp(`export interface ${exportName}\\b`);
  const match = fnRe.exec(source) ?? ifaceRe.exec(source);
  if (!match) return source;

  const start = match.index;
  let bodyStart = -1;

  if (match[0].includes('interface')) {
    bodyStart = source.indexOf('{', start);
  } else {
    let depth = 0;
    const paramOpen = source.indexOf('(', match.index);
    for (let i = paramOpen; i < source.length; i++) {
      const ch = source[i];
      if (ch === '(') depth++;
      else if (ch === ')') {
        depth--;
        if (depth === 0) {
          bodyStart = source.indexOf('{', i);
          break;
        }
      }
    }
  }

  if (bodyStart === -1) throw new Error(`Could not locate body for ${exportName}`);

  let depth = 0;
  for (let i = bodyStart; i < source.length; i++) {
    if (source[i] === '{') depth++;
    else if (source[i] === '}') {
      depth--;
      if (depth === 0) {
        let trimStart = start;
        while (trimStart > 0 && source[trimStart - 1] === '\n') trimStart--;
        let trimEnd = i + 1;
        while (trimEnd < source.length && source[trimEnd] === '\n') trimEnd++;
        return source.slice(0, trimStart) + source.slice(trimEnd);
      }
    }
  }
  throw new Error(`Unclosed block for ${exportName}`);
}

function generateDenoRegistryGate(): string {
  let src = readFileSync(LIB_PATH, 'utf8');
  src = src.replace(/^import type[^\n]+\n\n?/m, '');

  for (const name of CLIENT_ONLY) {
    src = removeExportBlock(src, name);
  }

  src = src.replace('export function normalizeHashForCompare', 'function normalizeHashForCompare');
  src = src.replace('export function isUnboundContractHash', 'function isUnboundContractHash');
  src = src.replace(
    /function isHighOrCriticalSeverity\(severity: Vulnerability\['severity'\]\): boolean \{\n  const s = severity as string;\n  return s === 'HIGH' \|\| s === 'CRITICAL';\n\}/,
    "function isHighOrCriticalSeverity(severity: string): boolean {\n  return severity === 'HIGH' || severity === 'CRITICAL';\n}"
  );

  // Drop orphan deploy-gate comment if canDeploy was removed.
  src = src.replace(/\n\/\*\* Deploy gate — same bar as validated status\. \*\/\n/g, '\n');

  return DENO_HEADER + src.trimStart() + '\n';
}

const checkOnly = process.argv.includes('--check');
const generated = generateDenoRegistryGate();
const existing = readFileSync(OUT_PATH, 'utf8');

if (checkOnly) {
  if (generated !== existing) {
    console.error(
      'registryGate drift: supabase/functions/_shared/registryGate.ts is out of sync with lib/registryGate.ts.\n' +
        'Run: npm run sync:registry-gate'
    );
    process.exit(1);
  }
  console.log('registryGate sync check passed.');
} else {
  if (generated !== existing) {
    writeFileSync(OUT_PATH, generated, 'utf8');
    console.log('Wrote', OUT_PATH);
  } else {
    console.log('registryGate already in sync.');
  }
}
