/**
 * Generates supabase/functions/_shared/registryGate.ts from lib/registryGate.ts
 * and syncs the dashboard inline gate block in publish-contract/index.dashboard.ts.
 *
 * Run: npm run sync:registry-gate
 * CI check: npm run sync:registry-gate -- --check
 */
import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const LIB_PATH = join(ROOT, 'lib', 'registryGate.ts');
const OUT_PATH = join(ROOT, 'supabase', 'functions', '_shared', 'registryGate.ts');
const DASHBOARD_PATH = join(ROOT, 'supabase', 'functions', 'publish-contract', 'index.dashboard.ts');
const DASHBOARD_GATE_START = '// --- registryGate (inlined for dashboard deploy) ---';
const DASHBOARD_GATE_END = '// --- end registryGate ---';

/** CI checks out LF; Windows working copies may use CRLF — compare normalized text only. */
function normalizeNewlines(text: string): string {
  return text.replace(/\r\n/g, '\n');
}

const DENO_HEADER = `// Deno edge bundle — generated by scripts/sync-registry-gate.ts — do not edit by hand.

interface Vulnerability {
  severity: string;
}

interface AuditReport {
  score?: number;
  total_score?: number;
  deployment_allowed?: boolean;
  vulnerabilities?: Vulnerability[];
  metadata?: { contract_hash?: string };
  timestamp?: number;
}

interface ContractArtifact {
  bytecode?: string;
}

`;

const CLIENT_ONLY = new Set([
  'DeployGateResult',
  'countHighOrCritical',
  'stampAuditWithSourceHash',
  'getContractSourceFromProject',
  'resolveAuditReportForPublish',
  'canDeploy',
]);

function removeExportBlock(source: string, exportName: string): string {
  const fnRe = new RegExp(`export (async )?function ${exportName}\\b`);
  const ifaceRe = new RegExp(`export interface ${exportName}\\b`);
  const match = fnRe.exec(source) ?? ifaceRe.exec(source);
  if (!match) return source;

  const start = match.index;
  let bodyStart = -1;

  if (match[0].includes('interface')) {
    bodyStart = source.indexOf('{', start);
  } else {
    let depth = 0;
    const paramOpen = source.indexOf('(', match.index);
    for (let i = paramOpen; i < source.length; i++) {
      const ch = source[i];
      if (ch === '(') depth++;
      else if (ch === ')') {
        depth--;
        if (depth === 0) {
          bodyStart = source.indexOf('{', i);
          break;
        }
      }
    }
  }

  if (bodyStart === -1) throw new Error(`Could not locate body for ${exportName}`);

  let depth = 0;
  for (let i = bodyStart; i < source.length; i++) {
    if (source[i] === '{') depth++;
    else if (source[i] === '}') {
      depth--;
      if (depth === 0) {
        let trimStart = start;
        while (trimStart > 0 && source[trimStart - 1] === '\n') trimStart--;
        let trimEnd = i + 1;
        while (trimEnd < source.length && source[trimEnd] === '\n') trimEnd++;
        return source.slice(0, trimStart) + source.slice(trimEnd);
      }
    }
  }
  throw new Error(`Unclosed block for ${exportName}`);
}

export function generateDenoRegistryGate(): string {
  let src = normalizeNewlines(readFileSync(LIB_PATH, 'utf8'));
  src = src.replace(/^import type[^\n]+\n\n?/m, '');

  for (const name of CLIENT_ONLY) {
    src = removeExportBlock(src, name);
  }

  src = src.replace('export function normalizeHashForCompare', 'function normalizeHashForCompare');
  src = src.replace('export function isUnboundContractHash', 'function isUnboundContractHash');
  src = src.replace(
    /function isHighOrCriticalSeverity\(severity: Vulnerability\['severity'\]\): boolean \{\n  const s = severity as string;\n  return s === 'HIGH' \|\| s === 'CRITICAL';\n\}/,
    "function isHighOrCriticalSeverity(severity: string): boolean {\n  return severity === 'HIGH' || severity === 'CRITICAL';\n}"
  );

  src = src.replace(/\n\/\*\* Deploy gate — same bar as validated status\. \*\/\n/g, '\n');

  return DENO_HEADER + src.trimStart() + '\n';
}

/** Dashboard paste-deploy: same logic as _shared, without export keywords. */
export function generateDashboardInlineGate(sharedGateSource: string): string {
  return sharedGateSource
    .replace(/^\/\/ Deno edge bundle[^\n]*\n\n/m, '')
    .replace(/^export /gm, '')
    .trimEnd();
}

export function syncDashboardGateFile(sharedGateSource: string): string {
  const dashboard = normalizeNewlines(readFileSync(DASHBOARD_PATH, 'utf8'));
  const startIdx = dashboard.indexOf(DASHBOARD_GATE_START);
  const endIdx = dashboard.indexOf(DASHBOARD_GATE_END);
  if (startIdx === -1 || endIdx === -1) {
    throw new Error(`Dashboard gate markers missing in ${DASHBOARD_PATH}`);
  }
  const inline = generateDashboardInlineGate(sharedGateSource);
  return (
    dashboard.slice(0, startIdx + DASHBOARD_GATE_START.length) +
    '\n' +
    inline +
    '\n' +
    dashboard.slice(endIdx)
  );
}

function runSync(checkOnly: boolean): void {
  const generatedShared = generateDenoRegistryGate();
  const existingShared = normalizeNewlines(readFileSync(OUT_PATH, 'utf8'));
  const generatedDashboard = syncDashboardGateFile(generatedShared);
  const existingDashboard = normalizeNewlines(readFileSync(DASHBOARD_PATH, 'utf8'));

  if (checkOnly) {
    let failed = false;
    if (generatedShared !== existingShared) {
      console.error(
        'registryGate drift: supabase/functions/_shared/registryGate.ts is out of sync.\n' +
          'Run: npm run sync:registry-gate'
      );
      failed = true;
    }
    if (generatedDashboard !== existingDashboard) {
      console.error(
        'registryGate drift: publish-contract/index.dashboard.ts inline gate is out of sync.\n' +
          'Run: npm run sync:registry-gate'
      );
      failed = true;
    }
    if (failed) process.exit(1);
    console.log('registryGate sync check passed (shared + dashboard).');
    return;
  }

  if (generatedShared !== existingShared) {
    writeFileSync(OUT_PATH, generatedShared, 'utf8');
    console.log('Wrote', OUT_PATH);
  } else {
    console.log('Shared registryGate already in sync.');
  }

  if (generatedDashboard !== existingDashboard) {
    writeFileSync(DASHBOARD_PATH, generatedDashboard, 'utf8');
    console.log('Wrote dashboard inline gate in', DASHBOARD_PATH);
  } else {
    console.log('Dashboard inline registryGate already in sync.');
  }
}

const checkOnly = process.argv.includes('--check');
runSync(checkOnly);
